namespace : ci-cd

on:
  push:
    branches:
      - main
      - dev

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: 
        uses: action/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: echo "🚀 Deploying to DEVELOPMENT environment"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: echo "🚀 Deploying to PRODUCTION environment"